version: '3.4'

networks:
  lsapi-dev:
    driver: bridge

services:
  lsapi:
    image: 'lecturesscheduler.webapi:latest'
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - '8000:80'
    environment:
      EndpointName: "LecturesScheduler.WebApi"
    networks:
      - lsapi-dev
    volumes:
      - ./certs:/etc/ssl/certs
volumes:
  lsapi_data:
    driver: local